M48
; DRILL file {KiCad (6.0.10)} date Fri Feb 17 15:36:54 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T15:36:54-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.0Y-2.7
X5.2Y-3.1
X5.6Y-2.9
X5.6888Y-2.6112
X5.7Y-3.0
X6.0Y-2.2
X6.1Y-2.8
X6.3Y-3.0
X6.3Y-3.1
X6.5Y-2.6
X6.5Y-3.2
T2
X5.5Y-2.1
X5.7Y-2.1
T0
M30
